version: '3'

services:
  cassandra-1:
    image: cassandra:4.1
    ports:
      - "9042:9042"
    networks:
      cassandra-net:
        aliases:
          - cassandra-1
    volumes:
      - cassandra-data1:/var/lib/cassandra
      - ./Data:/Data

  cassandra-2:
    image: cassandra:4.1
    environment:
      - CASSANDRA_SEEDS=cassandra-1
    ports:
      - "9043:9042"
    depends_on:
      - cassandra-1
    networks:
      cassandra-net:
        aliases:
          - cassandra-2
    volumes:
      - cassandra-data2:/var/lib/cassandra

  cassandra-3:
    image: cassandra:4.1
    environment:
      - CASSANDRA_SEEDS=cassandra-1
    ports:
      - "9044:9042"
    depends_on:
      - cassandra-2
    networks:
      cassandra-net:
        aliases:
          - cassandra-3
    volumes:
      - cassandra-data3:/var/lib/cassandra

volumes:
  cassandra-data1:
  cassandra-data2:
  cassandra-data3:

networks:
  cassandra-net:
    driver: bridge
